#!/bin/bash

docker rmi roaming-terminal:$USER

docker build \
	--build-arg USER_NAME=$USER \
	--build-arg USER_GID=$(id -g $USER) \
	--build-arg USER_UID=$(id -u $USER) \
	--tag roaming-terminal:$USER .
