#!/bin/bash

if [ "$HOME" = '' ]; then
  echo '$HOME is empty, cannot continue.'
  exit 1
fi

echo Using $HOME as home directory...

# Gather all folders in the home directory to mount as volumes

VOLUMES=""

for d in $HOME/*/
  do VOLUMES+=" -v ${d%*/}:${d%*/}"
done

# Create a pipe for sending commands back to the host using `remote`

PIPE_ID=$RANDOM
PIPE_PATH=$HOME/.roaming-pipe-$RANDOM

mkfifo $PIPE_PATH

while true; do eval "$(cat $PIPE_PATH)"; done &

LOOP_PID=$!

echo "Using roaming pipe: $PIPE_PATH"
echo "Running with additional args: [$1]"

if [ "$1" = 'init' ]; then

  mkdir --parents \
    $HOME/.azure \
    $HOME/.config/nvim \
    $HOME/.kube \
    $HOME/.roaming-home \
    $HOME/.ssh

  echo 'Run "p10k configure" to alter zsh prompt settings'
  echo 'Run "cp -r .cache .oh-my-zsh .p10k.zsh .profile .zshrc .roaming-home" to persist those settings for subsequent runs'

  eval "docker run -it --rm -w $(pwd) \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME:$HOME/.home \
    -v $HOME/.azure:$HOME/.azure \
    -v $HOME/.config:$HOME/.config \
    -v $HOME/.kube:$HOME/.kube \
    -v $HOME/.roaming-home:$HOME/.roaming-home \
    -v $HOME/.ssh:$HOME/.ssh \
    $VOLUMES \
    $2 \
    roaming-terminal:$USER"

else

  eval "docker run -it --rm -w $(pwd) \
    -v $PIPE_PATH:$HOME/.roaming-pipe \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /mnt/c:/mnt/c \
    -v $HOME:$HOME/.home \
    -v $HOME/.azure:$HOME/.azure \
    -v $HOME/.config:$HOME/.config \
    -v $HOME/.kube:$HOME/.kube \
    -v $HOME/.roaming-home/.cache:$HOME/.cache \
    -v $HOME/.roaming-home/.oh-my-zsh:$HOME/.oh-my-zsh \
    -v $HOME/.roaming-home/.p10k.zsh:$HOME/.p10k.zsh \
    -v $HOME/.roaming-home/.profile:$HOME/.profile \
    -v $HOME/.roaming-home/.zshrc:$HOME/.zshrc \
    -v $HOME/.ssh:$HOME/.ssh \
    $VOLUMES \
    $1 \
    roaming-terminal:$USER"

fi

kill $LOOP_PID

rm $PIPE_PATH
