#!/bin/bash

if [ "$HOME" = '' ]; then
  echo '$HOME is empty, cannot continue.'
  exit 1
fi

echo Using $HOME as home directory...

# Add permissions to the working folder

chmod o=rwx working

if [ "$1" = 'init' ]; then

  mkdir --parents \
    $HOME/.azure \
    $HOME/.config/nvim \
    $HOME/.kube \
    $HOME/.roaming-home \
    $HOME/.ssh \
    $HOME/syncs \
    $HOME/working

  docker run -it --rm -w $(pwd) \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME:$HOME/.home \
    -v $HOME/.azure:$HOME/.azure \
    -v $HOME/.config:$HOME/.config \
    -v $HOME/.kube:$HOME/.kube \
    -v $HOME/.roaming-home:$HOME/.roaming-home \
    -v $HOME/.ssh:$HOME/.ssh \
    -v $HOME/syncs:$HOME/syncs \
    -v $HOME/working:$HOME/working \
    roaming-terminal:$USER

elif [ "$1" = 'transient' ]; then

  docker run -it --rm -w $(pwd) \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /mnt/c:/mnt/c \
    -v $HOME:$HOME/.home \
    -v $HOME/.azure:$HOME/.azure \
    -v $HOME/.config:$HOME/.config \
    -v $HOME/.kube:$HOME/.kube \
    -v $HOME/.roaming-home/.cache:$HOME/.cache \
    -v $HOME/.roaming-home/.oh-my-zsh:$HOME/.oh-my-zsh \
    -v $HOME/.ssh:$HOME/.ssh \
    -v $HOME/syncs:$HOME/syncs \
    -v $HOME/working:$HOME/working \
    roaming-terminal:$USER

elif [ "$1" = 'start' ]; then

  docker run -it --name $USER-terminal \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /mnt/c:/mnt/c \
    -v $HOME:$HOME/.home \
    -v $HOME/.azure:$HOME/.azure \
    -v $HOME/.config:$HOME/.config \
    -v $HOME/.kube:$HOME/.kube \
    -v $HOME/.roaming-home/.cache:$HOME/.cache \
    -v $HOME/.roaming-home/.oh-my-zsh:$HOME/.oh-my-zsh \
    -v $HOME/.ssh:$HOME/.ssh \
    -v $HOME/syncs:$HOME/syncs \
    -v $HOME/working:$HOME/working \
    roaming-terminal:$USER

else

  docker start -a -i $USER-terminal 

fi


